### PR TITLE
Fix project name in generated new types

### PR DESCRIPTION
**Pull request by fancsali**

### CODE REVIEW

**Comment by sideeffect42** [comment]
Thanks for your PR, @fancsali.

I'm not sure if we actually want to keep the "cdist-community" project name.

This topic has been discussed in the cdist channel some time ago (2021-11-23) and my take away was that we keep the cdist name for the time being and then later on, either completely rename cdist-community to avoid confusion with cdist-ungleich or if cdist-community turns out to be the more active project, keep the name and "phase out" cdist-ungleich.

I'm not sure if the time is ready just yet to make that decision.
@4nd3r what do you think?

**Comment by Matze1224** [comment]
It looks like Nico is now more active on maintaining cdist-ungleich, which is the first point where people come to as newbies (because it's the official linked project).

I myself wanted to start a website which gives more insight to the different cdist repositories (mostly designed for types and also useful for type-only repositories). I've tried to start and noticed it will take it's time, also currently not having something near a base or any construct.
Also hoping it could help with patch management between the forks, but that's more to implement :-)

I will tell you when I've got something that it's worth to show.

**Comment by 4nd3r** [comment]
> I'm not sure if the time is ready just yet to make that decision.

imho ship has sailed and we just haven't come up with better name. chost? confh? :shrug:

**Comment by Matze1224** [comment]
From my view, as things are still compatible, I would just see different versions of cdist. Might be problematic when core features change/are added, but as of now, I won't see much differentiation.

It's just cdist-ungleich and cdist-community. Types are exchangeable between each other. They might ship a few different types and maybe a different ecosystem. And who knows how patches or features from the other project will be used, too?

As of today, there is no hard split inbetween the community and we can talk to each other. So it doesn't sound like an impossible thing to keep.

**Comment by 4nd3r** [comment]
> might be problematic when core features change/are added

Breakage in core side-features (stuff not related to `config`) will happen sooner or later. Same with types clean-up. This is not the place to discuss all the reasons why the fork happened, because I want to keep this place for technical discussions and not about harsh reality of the human situations. But as it was said in chat, and I agree, it's confusing with all other possible issues we don't know yet. We shouldn't hijack `cdist` name, just like bands should change the name when 90% of members are replaced and genre takes totally different direction :smile:

**Comment by 4nd3r** [comment]
Closing this PR due to project rename.

**Pull request closed without merging**
