### PR TITLE
update workflows

### PR DESCRIPTION
**Pull request by 4nd3r**
Ubuntu 18.04 is EOL soon. Also I rather not waste my precious time with EOL Pythons nor pypy.

Just defining major.minor is enough, latest patch version will be applied. 

`-latest` seems reasonable too.

### CODE REVIEW

**Comment by sideeffect42** [comment]
> Also I rather not waste my precious time with EOL Pythons nor pypy.

I'd rather keep all versions and variants of Python tested.
How do the additional workflows waste your time?

> Just defining major.minor is enough, latest patch version will be applied.
> 
> `-latest` seems reasonable too.

OK by me.

**Comment by 4nd3r** [comment]
> How do the additional test runs waste your time?

If something breaks for EOL Python, you have to fix it. Question isn't if, but when.

I don't feel comfortable encouraging usage of unmaintained software with unpatched security issues.

Also just plain waste of CPU resources.

**Comment by sideeffect42** [comment]
> If something breaks for EOL Python, you have to ~fix it~ work around it. Question isn't if, but when.

This hasn't really been an issue in the past. Work arounds for different Python versions were trivial.
I propose to leave things running as long as they run and revisit this topic when blockers show up.

> I don't feel comfortable encouraging usage of unmaintained software with unpatched security issues. Sooner or later GitHub will remove EOL stuff from Actions, so I rather not be in that club who contributes to holding back that decision.

Very hand-wavy.
Having the code CI tested on old versions does not imply that it is recommended to run the code this way in production; IMHO this is merely QA.
People will try to run code on old versions for whatever reason no matter if it is CI tested or not.

Also, bear in mind that just because a version is unmaintained upstream doesn't necessarily mean that it isn't patched (Python 2 is still included in most distros or Freexian's ELTS still supports Python 3.4/3.5 on old Debian).

In cdist(1) we are printing a warning when it is run on an old Python version:
https://github.com/skonfig/skonfig/blob/af10d29888ff587aca504d728475141c53892464/bin/cdist#L57-L65
We could do the same for skonfig(1) or produce a build-time warning if this makes you sleep better :-)

All that said, if we really care about security we should revisit transports (i.e. don't execute everything as root) and consider executing types in a sandbox.
This can solve many more security issues than any old Python version could have :-)

If GitHub Actions wants to remove the old Python versions, I'm pretty sure they will do it anyway no matter if little skonfig still uses them.

> Also just plain waste of CPU resources.

Our CI runs are very fast compared to other projects I've seen, so I don't really see this as an issue.
But in my POV we don't need to test all combinations on every push, so if there's a way to reduce the number of runs for the older versions I think that'd be fine.

**Comment by 4nd3r** [comment]
> All that said, if we really care about security

And that's whataboutism.

Compromise: unit-tests workflow only use supported versions. For legacy and other non-standard stuff create separate and purely informative workflow which only triggers on merge to main and not for pull requests.

**Comment by sideeffect42** [comment]
Compromise sounds good.
Makes pipelines less verbose and we can still discover possible issues and fix them if needed.

**Comment by 4nd3r** [comment]
Every workflow got `workflow_dispatch` for manual run. Can be run only if this PR is merged. Use case is for branches, which are not yet made into pull requests, but you want to run some workflows manually.

I think we need lint only needed for PRs.

Docs will be run for PRs and when push to main. As an idea, only for main results will be saved.

**Review by sideeffect42 — APPROVED** [review]
LGTM. Let's give it a shot.

**Pull request merged**
